# Imports

In [1]:
import pandas as pd
import sqlite3

In [2]:
df = pd.read_csv("wonka_choc_factory.csv")
df.head()

,Unnamed: 0,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product Name,Sales,Units,Gross Profit,Cost,Factory,Latitude,Longitude
0,0,2021-03-31,2026-09-26,Standard Class,128055,United States,San Francisco,California,94122,Chocolate,Pacific,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,Wicked Choccy's,32.076176,-81.088371
1,1,2021-03-31,2026-09-26,Standard Class,128055,United States,San Francisco,California,94122,Chocolate,Pacific,Wonka Bar -Scrumdiddlyumptious,7.20,2,5.00,2.20,Lot's O' Nuts,32.881893,-111.768036
2,2,2021-09-15,2027-03-13,Standard Class,138100,United States,New York City,New York,10011,Chocolate,Atlantic,Wonka Bar - Fudge Mallows,7.20,2,4.80,2.40,Lot's O' Nuts,32.881893,-111.768036
3,3,2021-09-15,2027-03-13,Standard Class,138100,United States,New York City,New York,10011,Chocolate,Atlantic,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42,Wicked Choccy's,32.076176,-81.088371
4,4,2022-10-04,2028-03-29,First Class,121391,United States,San Francisco,California,94109,Chocolate,Pacific,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,Wicked Choccy's,32.076176,-81.088371

# Data exploration

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      10194 non-null  int64
 1   Order Date      10194 non-null  object
 2   Ship Date       10194 non-null  object
 3   Ship Mode       10194 non-null  object
 4   Customer ID     10194 non-null  int64
 5   Country/Region  10194 non-null  object
 6   City            10194 non-null  object
 7   State/Province  10194 non-null  object
 8   Postal Code     10194 non-null  object
 9   Division        10194 non-null  object
 10  Region          10194 non-null  object
 11  Product Name    10194 non-null  object
 12  Sales           10194 non-null  float64
 13  Units           10194 non-null  int64
 14  Gross Profit    10194 non-null  float64
 15  Cost            10194 non-null  float64
 16  Factory         10194 non-null  object
 17  Latitude        10194 non-null  float64
 18  Longitude       10194 non-null  float64
dtypes: float64(5), int64(3), object(11)
memory usage: 1.5+ MB

In [4]:
df.shape

(10194, 19)

In [5]:
df.columns

Index(['Unnamed: 0', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Country/Region', 'City', 'State/Province', 'Postal Code', 'Division',
       'Region', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost',
       'Factory', 'Latitude', 'Longitude'],
      dtype='object')

## Drop unnecessary columns

In [6]:
df = df.drop(columns=[
    "Unnamed: 0",
    "Latitude",
    "Longitude",
    "Postal Code",
    "Ship Mode",
    "Ship Date" 
])

In [7]:
df.head()

,Order Date,Customer ID,Country/Region,City,State/Province,Division,Region,Product Name,Sales,Units,Gross Profit,Cost,Factory
0,2021-03-31,128055,United States,San Francisco,California,Chocolate,Pacific,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,Wicked Choccy's
1,2021-03-31,128055,United States,San Francisco,California,Chocolate,Pacific,Wonka Bar -Scrumdiddlyumptious,7.20,2,5.00,2.20,Lot's O' Nuts
2,2021-09-15,138100,United States,New York City,New York,Chocolate,Atlantic,Wonka Bar - Fudge Mallows,7.20,2,4.80,2.40,Lot's O' Nuts
3,2021-09-15,138100,United States,New York City,New York,Chocolate,Atlantic,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42,Wicked Choccy's
4,2022-10-04,121391,United States,San Francisco,California,Chocolate,Pacific,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,Wicked Choccy's

In [8]:
df=df.drop_duplicates()

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9881 entries, 0 to 10193
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order Date      9881 non-null   object
 1   Customer ID     9881 non-null   int64
 2   Country/Region  9881 non-null   object
 3   City            9881 non-null   object
 4   State/Province  9881 non-null   object
 5   Division        9881 non-null   object
 6   Region          9881 non-null   object
 7   Product Name    9881 non-null   object
 8   Sales           9881 non-null   float64
 9   Units           9881 non-null   int64
 10  Gross Profit    9881 non-null   float64
 11  Cost            9881 non-null   float64
 12  Factory         9881 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 1.1+ MB

In [10]:
df.isnull().sum()

Order Date        0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Division          0
Region            0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
Factory           0
dtype: int64

## Make Order date a date type

In [11]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9881 entries, 0 to 10193
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order Date      9881 non-null   datetime64[ns]
 1   Customer ID     9881 non-null   int64
 2   Country/Region  9881 non-null   object
 3   City            9881 non-null   object
 4   State/Province  9881 non-null   object
 5   Division        9881 non-null   object
 6   Region          9881 non-null   object
 7   Product Name    9881 non-null   object
 8   Sales           9881 non-null   float64
 9   Units           9881 non-null   int64
 10  Gross Profit    9881 non-null   float64
 11  Cost            9881 non-null   float64
 12  Factory         9881 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(2), object(7)
memory usage: 1.1+ MB

# Data wrangling

## Standardize titles

In [13]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_")
)

In [14]:
df.head()

,order_date,customer_id,country_region,city,state_province,division,region,product_name,sales,units,gross_profit,cost,factory
0,2021-03-31,128055,United States,San Francisco,California,Chocolate,Pacific,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,Wicked Choccy's
1,2021-03-31,128055,United States,San Francisco,California,Chocolate,Pacific,Wonka Bar -Scrumdiddlyumptious,7.20,2,5.00,2.20,Lot's O' Nuts
2,2021-09-15,138100,United States,New York City,New York,Chocolate,Atlantic,Wonka Bar - Fudge Mallows,7.20,2,4.80,2.40,Lot's O' Nuts
3,2021-09-15,138100,United States,New York City,New York,Chocolate,Atlantic,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42,Wicked Choccy's
4,2022-10-04,121391,United States,San Francisco,California,Chocolate,Pacific,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,Wicked Choccy's

## View unique values

In [15]:
df["state_province"].unique()

array(['California', 'New York', 'Texas', 'Minnesota', 'Nebraska',
       'Oregon', 'Tennessee', 'Arizona', 'Georgia', 'Rhode Island',
       'Connecticut', 'Missouri', 'Michigan', 'North Carolina',
       'Pennsylvania', 'Massachusetts', 'Oklahoma', 'Kentucky',
       'Washington', 'Virginia', 'New Hampshire', 'Indiana', 'Illinois',
       'British Columbia', 'Colorado', 'Ohio', 'Mississippi',
       'New Mexico', 'Florida', 'Louisiana', 'Montana', 'New Jersey',
       'Utah', 'Ontario', 'Nevada', 'Wisconsin', 'Alabama', 'Maryland',
       'South Carolina', 'Quebec', 'Iowa', 'Kansas', 'Delaware',
       'South Dakota', 'Vermont', 'Arkansas', 'North Dakota',
       'District of Columbia', 'Idaho', 'West Virginia', 'Alberta',
       'Prince Edward Island', 'Manitoba', 'Newfoundland and Labrador',
       'Maine', 'Wyoming', 'New Brunswick', 'Nova Scotia', 'Saskatchewan'],
      dtype=object)

In [16]:
df["city"].unique()

array(['San Francisco', 'New York City', 'Round Rock', 'Minneapolis',
       'Los Angeles', 'Rancho Cucamonga', 'Omaha', 'Salem', 'Lebanon',
       'Mesa', 'Atlanta', 'Providence', 'Middletown', 'Springfield',
       'Detroit', 'Concord', 'Chester', 'Lowell', 'Oklahoma City',
       'Georgetown', 'San Diego', 'Arlington', 'Seattle', 'Des Moines',
       'Waynesboro', 'Philadelphia', 'Greenwood', 'Indianapolis',
       'Houston', 'Phoenix', 'Portland', 'Pearland', 'Bloomington',
       'Henderson', 'Yonkers', 'Tulsa', 'Dallas', 'Long Beach',
       'Carrollton', 'Decatur', 'Vancouver', 'Louisville', 'Lakewood',
       'Toledo', 'Bellevue', 'Plano', 'Jackson', 'Lorain', 'Carlsbad',
       'Chicago', 'Jacksonville', 'Tucson', 'Avondale', 'Tampa',
       'Pembroke Pines', 'Lafayette', 'Beaumont', 'Rochester', 'Parma',
       'Lawrence', 'Huntsville', 'Great Falls', 'Fairfield',
       'San Clemente', 'Passaic', 'Homestead', 'College Station',
       'West Jordan', 'Toronto', 'Las Vegas', 'Franklin', 'Stockton',
       'Charlotte', 'Cincinnati', 'Knoxville', 'Alexandria',
       'Saint Petersburg', 'Peoria', 'Richmond', 'Allen', 'Milwaukee',
       'Columbus', 'Hampton', 'Waterbury', 'Eau Claire', 'Coral Springs',
       'Troy', 'Gulfport', 'Huntington Beach', 'Cranston', 'Aurora',
       'Bethlehem', 'Tamarac', 'Brentwood', 'Nashville', 'Anaheim',
       'Bartlett', 'Miami', 'Virginia Beach', 'Roswell', 'Plantation',
       'Coral Gables', 'Kent', 'Roseville', 'Glendale', 'Chesapeake',
       'Beverly', 'Palm Coast', 'Baltimore', 'Scottsdale', 'Apple Valley',
       'Wilmington', 'Taylor', 'Chandler', 'Grand Prairie', 'Cleveland',
       'Auburn', 'Des Plaines', 'Frisco', 'Florence', 'Malden',
       'Fort Lauderdale', 'Denver', 'Rock Hill', 'Fort Collins',
       'Montreal', 'Austin', 'Hattiesburg', 'Trenton', 'Woonsocket',
       'Quincy', 'Redmond', 'Pasadena', 'Irving', 'Charlottesville',
       'Montgomery', 'Longmont', 'Provo', 'Redondo Beach', 'Noblesville',
       'Palatine', 'Boynton Beach', 'Akron', 'Meriden', 'Bristol',
       'Morristown', 'Farmington', 'Bakersfield', 'Helena', 'Oceanside',
       'Wheeling', 'San Antonio', 'Sierra Vista', 'Inglewood',
       'Saint Charles', 'Fort Worth', 'Vineland', 'Columbia', 'Oakland',
       'El Cajon', 'Odessa', 'Laguna Niguel', 'Woodland', 'Green Bay',
       'Newport News', 'Fresno', 'Monroe', 'Lancaster', 'Lawton',
       'Bowling Green', 'Newark', 'Edmonds', 'Rome', 'Appleton', 'Olathe',
       'Fayetteville', 'Modesto', 'Raleigh', 'Sacramento', 'Albuquerque',
       'Memphis', 'The Colony', 'Greensboro', 'Watertown', 'Woodstock',
       'Garden City', 'Delray Beach', 'Quebec City', 'Hialeah',
       'Johnson City', 'San Bernardino', 'Santa Ana', 'Santa Barbara',
       'Gaithersburg', 'Montebello', 'Ann Arbor', 'Elyria',
       'Buffalo Grove', 'Deltona', 'Harrisonburg', 'Cary', 'Lakeville',
       'Broken Arrow', 'Plainfield', 'Oxnard', 'El Paso', 'Paterson',
       'Arvada', 'Spokane', 'Evanston', 'Skokie', 'Gilbert',
       'San Gabriel', 'Superior', 'Costa Mesa', 'Altoona', 'Littleton',
       'Frankfort', 'Clinton', 'Milford', 'Smyrna', 'Rapid City',
       'Port Arthur', 'Warwick', 'Hoover', 'Waco', 'Chattanooga',
       'Hamilton', 'Cedar Hill', 'East Orange', 'Cuyahoga Falls',
       'Camarillo', 'Burlington', 'Southaven', 'Chapel Hill', 'Owensboro',
       'La Porte', 'Westminster', 'Moorhead', 'Durham', 'Lubbock',
       'Lake Elsinore', 'Wichita', 'Medford', 'Tyler', 'Moreno Valley',
       'Shelton', 'Allentown', 'Hempstead', 'Apopka', 'Hillsboro',
       'Santa Clara', 'Mcallen', 'Everett', 'Renton', 'Orem',
       'Hot Springs', 'Marietta', 'Little Rock', 'Grove City', 'Linden',
       'Gresham', 'Urbandale', 'Reading', 'Colorado Springs',
       'New Bedford', 'Brownsville', 'Utica', 'North Charleston',
       'Redlands', 'Covington', 'Norwich', 'Elmhurst', 'Grand Rapids',
       'West Palm Beach', 'Lakeland', 'Freeport', 'Englewood',
       'Iowa City', 'Bossier City', 'Woodbury', 'Haltom City',
       'Hollywood', 'Dublin', 'San Jose', 'Fargo', 'Conroe', 'Pomona',
       'Thomasville', 'Fremont', 'Bozeman', 'Washington', 'Lake Forest',
       'Salinas', 'Marion', 'Port Saint Lucie', 'Hickory',
       'Salt Lake City', 'Riverside', 'Orlando', 'Asheville',
       'North Miami', 'Cottage Grove', 'Warner Robins', 'Dubuque',
       'Vallejo', 'Rockford', 'Orange', 'Murfreesboro', 'Tempe',
       'Kenosha', 'Miramar', 'Hendersonville', 'Westland', 'Abilene',
       'Keller', 'Greenville', 'Eagan', 'Romeoville', 'Las Cruces',
       'Thousand Oaks', 'Lincoln Park', 'Yuma', 'Encinitas', 'Pine Bluff',
       'New Albany', 'Meridian', 'Murray', 'Revere', 'Westfield',
       'Maple Grove', 'North Las Vegas', 'Tuscaloosa', 'Normal',
       'Lake Charles', 'Jamestown', 'Amarillo', 'Mason', 'Mansfield',
       'Buffalo', 'Redding', 'La Crosse', 'Laredo', 'Naperville', 'Lodi',
       'Jonesboro', 'Lansing', 'Escondido', 'Jefferson City', 'Dover',
       'Sandy Springs', 'Sioux Falls', 'Lehi', 'Dearborn Heights',
       'Saint Paul', 'Melbourne', 'Pueblo', 'Torrance', 'Mesquite',
       'Bryan', 'Bolingbrook', 'Mount Pleasant', 'Rogers', 'Bellingham',
       'Calgary', 'Edmonton', 'Antioch', 'Chico', 'Perth Amboy',
       'Richardson', 'Hesperia', 'Pharr', 'Leominster', 'Harlingen',
       'Texas City', 'Rio Rancho', 'Bullhead City', 'Cambridge', 'Kenner',
       'Boise', 'Loveland', 'Charlottetown', 'Mount Vernon', 'Sunnyvale',
       'Longview', 'Chula Vista', 'Danbury', 'Macon', 'Tallahassee',
       'Belleville', 'Coppell', 'Twin Falls', 'New Rochelle',
       'Broomfield', 'Winnipeg', 'Rockville', 'Manchester', 'Logan',
       'Sterling Heights', 'Sparks', 'Athens', 'Pocatello', 'Midland',
       'Holland', 'Saginaw', 'Waukesha', 'Niagara Falls', 'Atlantic City',
       'Olympia', 'Mobile', 'Garland', 'Reno', 'Kissimmee', 'Aberdeen',
       'Mission Viejo', 'Canton', 'Bridgeton', 'San Angelo', 'Draper',
       'Missoula', "St. John's", 'Davis', 'Madison', 'Port Orange',
       'Muskogee', 'Park Ridge', 'Ontario', 'Saint Cloud', 'Deer Park',
       'Tigard', 'Manteca', 'Highland Park', 'Pleasant Grove', 'Norman',
       'Layton', 'Overland Park', 'Springdale', 'Visalia', 'Clarksville',
       'Kirkwood', 'Hackensack', 'Tinley Park', 'Bangor', 'Thornton',
       'Champaign', 'Medina', 'Whittier', 'Elkhart', 'Suffolk',
       'La Quinta', 'Texarkana', 'Gladstone', 'Sheboygan', 'Cheyenne',
       'Citrus Heights', 'League City', 'Pasco', 'San Marcos',
       'Coachella', 'Saint Louis', 'Marysville', 'Corpus Christi',
       'Laurel', 'Mentor', 'Santa Fe', 'Lindenhurst', 'Sanford',
       'Moncton', 'Dearborn', 'Missouri City', 'Boca Raton', 'Wausau',
       'Conway', 'Coon Rapids', 'Parker', 'Grapevine', 'Santa Maria',
       'Royal Oak', 'York', 'Halifax', 'Edinburg', 'Oak Park', 'Danville',
       'Edmond', 'Wilson', 'Waterloo', 'Yucaipa', 'Orland Park',
       'Marlborough', 'Bayonne', 'Holyoke', 'Glenview', 'Andover',
       'Lewiston', 'Pompano Beach', 'Pensacola', 'Murrieta',
       'Commerce City', 'Billings', 'Gastonia', 'Mishawaka', 'Temecula',
       'Saint Peters', 'Independence', 'Daytona Beach', 'Morgan Hill',
       'East Point', 'Manhattan', 'Carol Stream', 'South Bend',
       'Summerville', 'Burbank', 'La Mesa', 'Margate', 'Rochester Hills',
       'Arlington Heights', 'Bedford', 'Clifton', 'Goldsboro',
       'New Castle', 'Baytown', 'Caldwell', 'New Brunswick', 'Regina',
       'Greeley', 'Redwood City', 'San Luis Obispo', 'Nashua', 'Oswego',
       'Norfolk', 'Pico Rivera', 'Hagerstown', 'Jupiter', 'Vacaville',
       'Grand Island', 'Eugene', 'Cedar Rapids', 'Ormond Beach',
       'West Allis', 'Clovis', 'San Mateo', 'Portage'], dtype=object)

In [17]:
df["region"].unique()

array(['Pacific', 'Atlantic', 'Interior', 'Gulf'], dtype=object)

In [18]:
df["factory"].unique()

array(["Wicked Choccy's", "Lot's O' Nuts", 'Secret Factory',
       'Sugar Shack', 'The Other Factory'], dtype=object)

In [19]:
df["country_region"].unique()

array(['United States', 'Canada'], dtype=object)

In [20]:
df["product_name"].unique()

array(['Wonka Bar - Triple Dazzle Caramel',
       'Wonka Bar -Scrumdiddlyumptious', 'Wonka Bar - Fudge Mallows',
       'Wonka Bar - Milk Chocolate', 'Wonka Bar - Nutty Crunch Surprise',
       'Wonka Gum', 'SweeTARTS', 'Lickable Wallpaper', 'Kazookles',
       'Everlasting Gobstopper', 'Fizzy Lifting Drinks', 'Nerds',
       'Fun Dip', 'Laffy Taffy', 'Hair Toffee'], dtype=object)

## Double check and erase if there are other string problems (invicible spaces...)

In [23]:
text_cols = [
    "country_region",
    "city",
    "state_province",
    "division",
    "region",
    "product_name",
    "factory"
]

for col in text_cols:
    df[col] = df[col].str.strip()

In [24]:
df.head()

,order_date,customer_id,country_region,city,state_province,division,region,product_name,sales,units,gross_profit,cost,factory
0,2021-03-31,128055,United States,San Francisco,California,Chocolate,Pacific,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,Wicked Choccy's
1,2021-03-31,128055,United States,San Francisco,California,Chocolate,Pacific,Wonka Bar -Scrumdiddlyumptious,7.20,2,5.00,2.20,Lot's O' Nuts
2,2021-09-15,138100,United States,New York City,New York,Chocolate,Atlantic,Wonka Bar - Fudge Mallows,7.20,2,4.80,2.40,Lot's O' Nuts
3,2021-09-15,138100,United States,New York City,New York,Chocolate,Atlantic,Wonka Bar - Milk Chocolate,9.75,3,6.33,3.42,Wicked Choccy's
4,2022-10-04,121391,United States,San Francisco,California,Chocolate,Pacific,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,Wicked Choccy's